#!/bin/sh
#
# Copyright (C) 2013 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


case "$1" in
    configure)
	if ! omv_config_exists "/config/services/vdrplugin"; then
	    echo "Initialize OMV VDR plugin configuration"
        # VDR Part
	        object="<vdr_enable>0</vdr_enable>"
	        object="${object}<vdr_transpondertype>c</vdr_transpondertype>"
            object="${object}<vdr_atsc_country> </vdr_atsc_country>"
            object="${object}<vdr_atsc_type>3</vdr_atsc_type>"
            object="${object}<vdr_atsc_scan_encrypted>0</vdr_atsc_scan_encrypted>"
            object="${object}<vdr_dvb_t_country> </vdr_dvb_t_country>"
            object="${object}<vdr_dvb_t_scan_encrypted>0</vdr_dvb_t_scan_encrypted>"
            object="${object}<vdr_dvb_c_country> </vdr_dvb_c_country>"
            object="${object}<vdr_dvb_c_qam> </vdr_dvb_c_qam>"
            object="${object}<vdr_dvb_c_symbolrate> </vdr_dvb_c_symbolrate>"
            object="${object}<vdr_dvb_c_extended_qam>0</vdr_dvb_c_extended_qam>"
            object="${object}<vdr_dvb_c_scan_encrypted>0</vdr_dvb_c_scan_encrypted>"
            object="${object}<vdr_dvb_s_country> </vdr_dvb_s_country>"
            object="${object}<vdr_dvb_s_satellite> </vdr_dvb_s_satellite>"
            object="${object}<vdr_dvb_s_scan_encrypted>0</vdr_dvb_s_scan_encrypted>"
	        object="${object}<vdr_recordingdir></vdr_recordingdir>"
	        object="${object}<vdr_maxfilesize_gb>5</vdr_maxfilesize_gb>"
	        object="${object}<vdr_epglanguage></vdr_epglanguage>"
            object="${object}<vdr_subtitles></vdr_subtitles>"
            object="${object}<vdr_subtitle_languages></vdr_subtitle_languages>"
	        object="${object}<vdr_channelupdatemode>1</vdr_channelupdatemode>"

        # VDR Admin-am
	        object="${object}<vdradminam_enable>0</vdradminam_enable>"
	        object="${object}<vdradminam_port>8001</vdradminam_port>"

	    omv_config_add_element "/config/services" "vdrplugin" "${object}" true
	fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
