#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge|remove|abort-install|disappear)
        omv_config_delete "/config/services/vdr"
    ;;

    upgrade|failed-upgrade|abort-upgrade)
        echo "Configuration left untouched"
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
