#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/vdr"

case "$1" in
    purge|remove|abort-install|disappear)
    	if omv_config_exists $CONFIG; then
            echo "Deleting Configuration"
            omv_config_delete $CONFIG;
        fi

    	if ! omv_config_exists $CONFIG; then
            echo "Configuration Deleted"
    	fi
    ;;

    upgrade|failed-upgrade|abort-upgrade)
        echo "Configuration left untouched"
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
