#!/bin/sh
#
# Copyright (C) 2013 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Start and stop VDR inorder to generate the original configuration files
sleep 2
VDR_CONFIG_FILE="/etc/default/vdr"
sed -i '/ENABLED=/c\ENABLED=1' $VDR_CONFIG_FILE

/etc/init.d/vdr start
sleep 2
/etc/init.d/vdr stop
/etc/init.d/vdradmin-am stop

sed -i '/ENABLED=/c\ENABLED=0' $VDR_CONFIG_FILE
