#!/bin/sh
#
# Copyright (C) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_VDR_ORDER_CONF="/etc/vdr/plugins/order.conf"

cat <<EOF > ${OMV_VDR_ORDER_CONF}
#
# If you like a fixed plugin order in your menu place the plugin base names
# here. Remember that the first entry a plugin may get, starts at five in
# VDR's OSD.
#
# A '*' will be a treated as a placeholder for all remaining plugins which
# are installed but not explicitly listed here.
#
# If you want a certain Plugin not to be loaded automatically at
# vdr-startup, then you can simply write "-pluginname" in this file.
#
# Plugins which are not installed will be silently ignored.
#
# If you want to add commandline-options for a certain plugin, this file is
# not the right place - you can add them in the file(s)
# /etc/vdr/plugins/plugin.<pluginname>.conf - each option in one line

*
EOF
